const express = require("express")
const router = express.Router()
const {createUser,loginUser,getAllUser,getUser,UpdateUser,deleteUser,blockUser,unblockUser,refreshToken,updatePassword, forgotPasswordToken,logout, resetPassword} = require("../controllers/userCtrl")
const authMiddleware = require("../middlewares/authentication")
const isAdmin = require("../middlewares/isAdmin")

router.route("/login").post(loginUser)
router.route("/").get(authMiddleware, getAllUser).post(createUser)
router.route("/refreshToken").get(authMiddleware,refreshToken)
router.route("/:id").get(authMiddleware, getUser)
.patch(authMiddleware, UpdateUser)
.delete(authMiddleware, deleteUser)
router.route("/blockuser/:id").patch(authMiddleware, isAdmin, blockUser)
router.route("/unblockuser/:id").patch(authMiddleware, isAdmin, unblockUser)
router.route("/updatePassword").put(authMiddleware,updatePassword)
router.route("/forgotPasswordToken").post(forgotPasswordToken)
router.route("/resetPassword/:token").put(resetPassword)
router.route("/logout").post(authMiddleware,logout) 

module.exports = router